apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdh
  namespace: openshift-gitops
spec:
  destination:
    namespace: rhdh-operator
    server: https://kubernetes.default.svc
  project: cluster-app
  sources:
  - repoURL: git@github.com:StinkyBenji/rhdh-playground.git
    path: rhdh/operator
  - repoURL: git@github.com:StinkyBenji/rhdh-playground.git
    path: rhdh/instance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      