kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
  namespace: rhdh-operator
data:
  app-config-rhdh.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://backstage-developer-hub-rhdh-operator.apps.ocp4.whatever.out-of-my-head.de

    enabled:
     github: true

    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}
    auth:
      allowGuestAccess: true
      environment: development
      providers:
        github:
          development:
            clientId: ${GITHUB_APP_CLIENT_ID}
            clientSecret: ${GITHUB_APP_CLIENT_SECRET}

    backend:
      auth:
        keys:
          - secret: "${BACKEND_SECRET}"
      baseUrl: https://backstage-developer-hub-rhdh-operator.apps.ocp4.whatever.out-of-my-head.de
      cors:
        origin: https://backstage-developer-hub-rhdh-operator.apps.ocp4.whatever.out-of-my-head.de