apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: developer-hub
  namespace: rhdh-operator
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: app-config-rhdh
    dynamicPluginsConfigMapName: dynamic-plugins-rhdhQ
    extraFiles:
      mountPath: /opt/app-root/src
    extraEnvs:
      secrets:
        - name: github-auth-rhdh
        - name: github-token-rhdh
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
